"""DuckDB persistence layer for entity resolution.

DuckDB is so much nicer than sqlite for analytics stuff - it handles JSON natively,
does columnar storage, and the SQL syntax is way more modern. Plus it's embedded
so no server to manage.

The schema here tracks the full entity resolution workflow:
  1. records - raw data ingested from CSV/JSON/Parquet files
  2. candidate_pairs - potential matches found by blocking or ANN search
  3. pair_scores - detailed similarity scores for each candidate
  4. review_decisions - human feedback on uncertain matches
  5. entity_clusters - final resolved entities (groups of matching records)

TODO: add streamlit dashboard for review UI - the CLI works but a visual
interface would be way better for reviewing hundreds of uncertain pairs
"""

import json
from pathlib import Path

import duckdb
import structlog

from resolve_ai.models import (
    CandidatePair,
    MatchClassification,
    PairScores,
    Record,
    ReviewDecision,
)

log = structlog.get_logger()

# structlog gives us nice structured logs that are easy to parse later
# could pipe these into elasticsearch or something for production monitoring

# schema is idempotent - can run multiple times without issues
# the CHECK constraints on classification/decision catch bugs early
SCHEMA_SQL = """
-- Records ingested from source files
CREATE TABLE IF NOT EXISTS records (
    record_id TEXT PRIMARY KEY,
    source_file TEXT NOT NULL,
    source_row INTEGER NOT NULL,
    raw_data JSON NOT NULL,
    name_normalized TEXT,
    address_normalized TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Candidate pairs generated by blocking/ANN
CREATE TABLE IF NOT EXISTS candidate_pairs (
    pair_id TEXT PRIMARY KEY,
    record_id_a TEXT NOT NULL,
    record_id_b TEXT NOT NULL,
    generation_method TEXT,
    embedding_similarity FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Detailed scores for each candidate pair
-- llm_score is None for now - will add ollama integration later
-- keeping the column so we don't need a migration when we add it
CREATE TABLE IF NOT EXISTS pair_scores (
    pair_id TEXT PRIMARY KEY,
    levenshtein_ratio FLOAT,
    jaro_winkler FLOAT,
    token_sort_ratio FLOAT,
    cosine_similarity FLOAT,
    llm_score FLOAT,              -- this is where LLM would help disambiguate uncertain pairs
    llm_reasoning TEXT,           -- store the LLM's explanation for auditing
    composite_score FLOAT NOT NULL,
    classification TEXT CHECK (classification IN ('match', 'no_match', 'uncertain')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Human review decisions
CREATE TABLE IF NOT EXISTS review_decisions (
    pair_id TEXT PRIMARY KEY,
    decision TEXT CHECK (decision IN ('match', 'no_match', 'skip')),
    reviewer TEXT,
    notes TEXT,
    reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Final resolved entities (clusters of matching records)
CREATE TABLE IF NOT EXISTS entity_clusters (
    cluster_id TEXT,
    record_id TEXT,
    confidence FLOAT,
    PRIMARY KEY (cluster_id, record_id)
);
"""


class Database:
    """DuckDB database for entity resolution storage."""

    def __init__(self, db_path: Path | str = ":memory:"):
        """Initialize database connection.

        Args:
            db_path: Path to database file or ":memory:" for in-memory.
        """
        self.db_path = Path(db_path) if db_path != ":memory:" else db_path
        # lazy db connection so tests can use :memory: without hitting disk
        self._conn: duckdb.DuckDBPyConnection | None = None

    @property
    def conn(self) -> duckdb.DuckDBPyConnection:
        """Get or create database connection.

        lazy initialization means we don't create the file until first query -
        useful when you just want to instantiate the class to check config
        """
        if self._conn is None:
            self._conn = duckdb.connect(str(self.db_path))
            self._init_schema()
        return self._conn

    def _init_schema(self) -> None:
        """Initialize database schema."""
        self.conn.execute(SCHEMA_SQL)
        log.info("database_initialized", path=str(self.db_path))

    def close(self) -> None:
        """Close database connection."""
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    # Record operations
    def insert_records(self, records: list[Record]) -> int:
        """Insert records into the database.

        Args:
            records: List of records to insert.

        Returns:
            Number of records inserted.
        """
        if not records:
            return 0

        # ON CONFLICT DO UPDATE is way cleaner than checking existence first
        # also handles the case where you re-ingest the same file with updates
        for record in records:
            self.conn.execute(
                """
                INSERT INTO records
                (record_id, source_file, source_row, raw_data, name_normalized, address_normalized)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT (record_id) DO UPDATE SET
                    raw_data = EXCLUDED.raw_data,
                    name_normalized = EXCLUDED.name_normalized,
                    address_normalized = EXCLUDED.address_normalized
                """,
                [
                    record.record_id,
                    record.source_file,
                    record.source_row,
                    json.dumps(record.raw_data),
                    record.name_normalized,
                    record.address_normalized,
                ],
            )

        log.info("records_inserted", count=len(records))
        return len(records)

    def get_record(self, record_id: str) -> Record | None:
        """Get a record by ID.

        Args:
            record_id: The record ID.

        Returns:
            The record or None if not found.
        """
        result = self.conn.execute(
            "SELECT * FROM records WHERE record_id = ?", [record_id]
        ).fetchone()

        if result is None:
            return None

        return Record(
            record_id=result[0],
            source_file=result[1],
            source_row=result[2],
            raw_data=json.loads(result[3]) if isinstance(result[3], str) else result[3],
            name_normalized=result[4],
            address_normalized=result[5],
        )

    def get_all_records(self) -> list[Record]:
        """Get all records from the database.

        Returns:
            List of all records.
        """
        results = self.conn.execute("SELECT * FROM records").fetchall()
        records = []
        for row in results:
            records.append(
                Record(
                    record_id=row[0],
                    source_file=row[1],
                    source_row=row[2],
                    raw_data=json.loads(row[3]) if isinstance(row[3], str) else row[3],
                    name_normalized=row[4],
                    address_normalized=row[5],
                )
            )
        return records

    # Candidate pair operations
    def insert_candidate_pairs(self, pairs: list[CandidatePair]) -> int:
        """Insert candidate pairs into the database.

        Args:
            pairs: List of candidate pairs.

        Returns:
            Number of pairs inserted.
        """
        if not pairs:
            return 0

        for pair in pairs:
            self.conn.execute(
                """
                INSERT INTO candidate_pairs
                (pair_id, record_id_a, record_id_b, generation_method, embedding_similarity)
                VALUES (?, ?, ?, ?, ?)
                ON CONFLICT (pair_id) DO UPDATE SET
                    generation_method = EXCLUDED.generation_method,
                    embedding_similarity = EXCLUDED.embedding_similarity
                """,
                [
                    pair.pair_id,
                    pair.record_id_a,
                    pair.record_id_b,
                    pair.generation_method,
                    pair.embedding_similarity,
                ],
            )

        log.info("candidate_pairs_inserted", count=len(pairs))
        return len(pairs)

    # Pair scores operations
    def insert_pair_scores(self, scores: list[PairScores]) -> int:
        """Insert pair scores into the database.

        Args:
            scores: List of pair scores.

        Returns:
            Number of scores inserted.
        """
        if not scores:
            return 0

        for score in scores:
            self.conn.execute(
                """
                INSERT INTO pair_scores
                (pair_id, levenshtein_ratio, jaro_winkler, token_sort_ratio,
                 cosine_similarity, llm_score, llm_reasoning, composite_score, classification)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (pair_id) DO UPDATE SET
                    levenshtein_ratio = EXCLUDED.levenshtein_ratio,
                    jaro_winkler = EXCLUDED.jaro_winkler,
                    token_sort_ratio = EXCLUDED.token_sort_ratio,
                    cosine_similarity = EXCLUDED.cosine_similarity,
                    llm_score = EXCLUDED.llm_score,
                    llm_reasoning = EXCLUDED.llm_reasoning,
                    composite_score = EXCLUDED.composite_score,
                    classification = EXCLUDED.classification
                """,
                [
                    score.pair_id,
                    score.levenshtein_ratio,
                    score.jaro_winkler,
                    score.token_sort_ratio,
                    score.cosine_similarity,
                    score.llm_score,
                    score.llm_reasoning,
                    score.composite_score,
                    score.classification.value,
                ],
            )

        log.info("pair_scores_inserted", count=len(scores))
        return len(scores)

    def get_scores_by_classification(
        self, classification: MatchClassification
    ) -> list[tuple[PairScores, Record, Record]]:
        """Get pair scores by classification with associated records.

        This query joins across three tables which isn't super efficient for
        large datasets - might want to add indexes on pair_scores.classification
        and candidate_pairs.pair_id if this becomes a bottleneck.

        Args:
            classification: The classification to filter by.

        Returns:
            List of (PairScores, record_a, record_b) tuples.
        """
        # TODO: add pagination for large result sets - this loads everything into memory
        results = self.conn.execute(
            """
            SELECT
                ps.*,
                ra.record_id, ra.source_file, ra.source_row, ra.raw_data,
                ra.name_normalized, ra.address_normalized,
                rb.record_id, rb.source_file, rb.source_row, rb.raw_data,
                rb.name_normalized, rb.address_normalized
            FROM pair_scores ps
            JOIN candidate_pairs cp ON ps.pair_id = cp.pair_id
            JOIN records ra ON cp.record_id_a = ra.record_id
            JOIN records rb ON cp.record_id_b = rb.record_id
            WHERE ps.classification = ?
            ORDER BY ps.composite_score DESC
            """,
            [classification.value],
        ).fetchall()

        pairs = []
        for row in results:
            score = PairScores(
                pair_id=row[0],
                levenshtein_ratio=row[1],
                jaro_winkler=row[2],
                token_sort_ratio=row[3],
                cosine_similarity=row[4],
                llm_score=row[5],
                llm_reasoning=row[6],
                composite_score=row[7],
                classification=MatchClassification(row[8]),
            )
            record_a = Record(
                record_id=row[10],
                source_file=row[11],
                source_row=row[12],
                raw_data=json.loads(row[13]) if isinstance(row[13], str) else row[13],
                name_normalized=row[14],
                address_normalized=row[15],
            )
            record_b = Record(
                record_id=row[16],
                source_file=row[17],
                source_row=row[18],
                raw_data=json.loads(row[19]) if isinstance(row[19], str) else row[19],
                name_normalized=row[20],
                address_normalized=row[21],
            )
            pairs.append((score, record_a, record_b))

        return pairs

    # Review operations
    def insert_review_decision(self, decision: ReviewDecision) -> None:
        """Insert a review decision.

        Args:
            decision: The review decision.
        """
        self.conn.execute(
            """
            INSERT INTO review_decisions
            (pair_id, decision, reviewer, notes, reviewed_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT (pair_id) DO UPDATE SET
                decision = EXCLUDED.decision,
                reviewer = EXCLUDED.reviewer,
                notes = EXCLUDED.notes,
                reviewed_at = EXCLUDED.reviewed_at
            """,
            [
                decision.pair_id,
                decision.decision,
                decision.reviewer,
                decision.notes,
                decision.reviewed_at.isoformat(),
            ],
        )

    def get_unreviewed_uncertain_pairs(
        self, limit: int = 10
    ) -> list[tuple[PairScores, Record, Record]]:
        """Get uncertain pairs that haven't been reviewed.

        Args:
            limit: Maximum number of pairs to return.

        Returns:
            List of (PairScores, record_a, record_b) tuples.
        """
        results = self.conn.execute(
            """
            SELECT
                ps.*,
                ra.record_id, ra.source_file, ra.source_row, ra.raw_data,
                ra.name_normalized, ra.address_normalized,
                rb.record_id, rb.source_file, rb.source_row, rb.raw_data,
                rb.name_normalized, rb.address_normalized
            FROM pair_scores ps
            JOIN candidate_pairs cp ON ps.pair_id = cp.pair_id
            JOIN records ra ON cp.record_id_a = ra.record_id
            JOIN records rb ON cp.record_id_b = rb.record_id
            LEFT JOIN review_decisions rd ON ps.pair_id = rd.pair_id
            WHERE ps.classification = 'uncertain'
              AND rd.pair_id IS NULL
            ORDER BY ps.composite_score DESC
            LIMIT ?
            """,
            [limit],
        ).fetchall()

        pairs = []
        for row in results:
            score = PairScores(
                pair_id=row[0],
                levenshtein_ratio=row[1],
                jaro_winkler=row[2],
                token_sort_ratio=row[3],
                cosine_similarity=row[4],
                llm_score=row[5],
                llm_reasoning=row[6],
                composite_score=row[7],
                classification=MatchClassification(row[8]),
            )
            record_a = Record(
                record_id=row[10],
                source_file=row[11],
                source_row=row[12],
                raw_data=json.loads(row[13]) if isinstance(row[13], str) else row[13],
                name_normalized=row[14],
                address_normalized=row[15],
            )
            record_b = Record(
                record_id=row[16],
                source_file=row[17],
                source_row=row[18],
                raw_data=json.loads(row[19]) if isinstance(row[19], str) else row[19],
                name_normalized=row[20],
                address_normalized=row[21],
            )
            pairs.append((score, record_a, record_b))

        return pairs

    # Statistics
    def get_statistics(self) -> dict:
        """Get matching statistics.

        Returns:
            Dictionary of statistics.
        """
        stats = {}

        # Record count
        result = self.conn.execute("SELECT COUNT(*) FROM records").fetchone()
        stats["total_records"] = result[0] if result else 0

        # Candidate pair count
        result = self.conn.execute("SELECT COUNT(*) FROM candidate_pairs").fetchone()
        stats["total_candidate_pairs"] = result[0] if result else 0

        # Scores by classification
        results = self.conn.execute(
            """
            SELECT classification, COUNT(*) as count
            FROM pair_scores
            GROUP BY classification
            """
        ).fetchall()

        stats["matches"] = 0
        stats["no_matches"] = 0
        stats["uncertain"] = 0

        for row in results:
            if row[0] == "match":
                stats["matches"] = row[1]
            elif row[0] == "no_match":
                stats["no_matches"] = row[1]
            elif row[0] == "uncertain":
                stats["uncertain"] = row[1]

        # Review decisions
        result = self.conn.execute("SELECT COUNT(*) FROM review_decisions").fetchone()
        stats["reviewed"] = result[0] if result else 0

        return stats

    def export_matches(self, output_path: Path, format: str = "csv") -> None:
        """Export matches to a file.

        Exports include both auto-matches (high confidence) and human-reviewed matches.
        The review_decision column lets downstream systems know if a match was
        verified by a human.

        Args:
            output_path: Path to output file.
            format: Output format ('csv' or 'json').
        """
        # include both algorithmic matches AND human-approved matches
        results = self.conn.execute(
            """
            SELECT
                cp.pair_id,
                cp.record_id_a,
                cp.record_id_b,
                ra.raw_data as record_a_data,
                rb.raw_data as record_b_data,
                ps.composite_score,
                ps.classification,
                rd.decision as review_decision
            FROM candidate_pairs cp
            JOIN records ra ON cp.record_id_a = ra.record_id
            JOIN records rb ON cp.record_id_b = rb.record_id
            JOIN pair_scores ps ON cp.pair_id = ps.pair_id
            LEFT JOIN review_decisions rd ON cp.pair_id = rd.pair_id
            WHERE ps.classification = 'match'
               OR rd.decision = 'match'
            ORDER BY ps.composite_score DESC
            """
        ).fetchall()

        if format == "csv":
            import csv

            with open(output_path, "w", newline="") as f:
                writer = csv.writer(f)
                writer.writerow(
                    [
                        "pair_id",
                        "record_id_a",
                        "record_id_b",
                        "record_a_data",
                        "record_b_data",
                        "score",
                        "classification",
                        "review_decision",
                    ]
                )
                for row in results:
                    writer.writerow(row)
        else:
            matches = []
            for row in results:
                matches.append(
                    {
                        "pair_id": row[0],
                        "record_id_a": row[1],
                        "record_id_b": row[2],
                        "record_a_data": row[3],
                        "record_b_data": row[4],
                        "score": row[5],
                        "classification": row[6],
                        "review_decision": row[7],
                    }
                )
            with open(output_path, "w") as f:
                json.dump(matches, f, indent=2)

        log.info("matches_exported", path=str(output_path), count=len(results))
