"""Pydantic models for entity resolution.

using pydantic for validation so we catch bad data early - saved me a lot of
debugging when I was getting weird scores from the embedding service. the
Field constraints (ge=0.0, le=1.0) have caught several off-by-one bugs.

these models map pretty directly to the database schema in storage/database.py
"""

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class MatchClassification(str, Enum):
    """Classification of a candidate pair.

    the three-way classification is key to the workflow:
    - MATCH: high confidence, auto-approve
    - NO_MATCH: low confidence, auto-reject
    - UNCERTAIN: needs human review (this is where LLM could help)
    """

    MATCH = "match"
    NO_MATCH = "no_match"
    UNCERTAIN = "uncertain"


class Record(BaseModel):
    """A record ingested from a data source.

    Keeps both raw_data (original) and normalized fields so you can always
    go back to the source. The normalized fields are what we actually use
    for matching.
    """

    record_id: str  # either from source data or auto-generated UUID
    source_file: str  # track provenance for debugging
    source_row: int  # useful when you need to fix upstream data
    raw_data: dict  # original row as-is from the CSV/JSON
    name_normalized: str | None = None  # lowercase, whitespace stripped, etc.
    address_normalized: str | None = None
    created_at: datetime = Field(default_factory=datetime.now)


class CandidatePair(BaseModel):
    """A pair of records that are candidates for matching.

    These are generated by the candidate generation step - we don't compare
    all pairs (O(n^2) would be brutal), just the ones that have a reasonable
    chance of matching based on blocking keys or embedding similarity.
    """

    pair_id: str  # deterministic: sorted hash of record_id_a + record_id_b
    record_id_a: str
    record_id_b: str
    generation_method: str  # 'ann', 'blocking', 'both' - useful for debugging
    embedding_similarity: float  # from ANN search, -1 if from blocking only


class PairScores(BaseModel):
    """Detailed scores for a candidate pair.

    We compute multiple similarity metrics because no single one is perfect:
    - levenshtein catches character-level edits (typos)
    - jaro-winkler is good for names (weights prefix matches higher)
    - token_sort handles word reordering ("John Smith" vs "Smith, John")
    - cosine_similarity captures semantic meaning via embeddings

    The composite_score combines these with configurable weights.
    """

    pair_id: str
    levenshtein_ratio: float = Field(ge=0.0, le=1.0)
    jaro_winkler: float = Field(ge=0.0, le=1.0)
    token_sort_ratio: float = Field(ge=0.0, le=1.0)  # from fuzzywuzzy, handles word order
    cosine_similarity: float  # embedding dot product, clamped below
    llm_score: float | None = Field(default=None, ge=0.0, le=1.0)  # TODO: ollama integration
    llm_reasoning: str | None = None  # LLM's explanation for the score
    composite_score: float  # weighted combination, used for classification
    classification: MatchClassification

    @field_validator("cosine_similarity", "composite_score", mode="before")
    @classmethod
    def clamp_score(cls, v: float) -> float:
        """Clamp score to handle floating point precision issues.

        sometimes embeddings give us values like 1.0000001 due to floating point
        weirdness - this prevents pydantic from rejecting valid data
        """
        return max(0.0, min(1.0, v))


class ReviewDecision(BaseModel):
    """Human review decision for a candidate pair.

    The human-in-the-loop part of the system. Reviewers see uncertain pairs
    and make the final call. Notes field is optional but super helpful for
    training data if we want to fine-tune a model later.
    """

    pair_id: str
    decision: Literal["match", "no_match", "skip"]  # skip = "come back to this later"
    reviewer: str = "cli_user"  # could be username from auth system
    notes: str | None = None  # "same person, different addresses" etc.
    reviewed_at: datetime = Field(default_factory=datetime.now)


class EntityCluster(BaseModel):
    """A cluster of records representing the same entity.

    TODO: implement transitive closure to build these from pairwise matches.
    Right now we just have pairs, but ultimately we want clusters like:
    {cluster_id: "abc", record_ids: ["rec1", "rec2", "rec3"], confidence: 0.95}

    Need to handle the case where A matches B and B matches C but A doesn't
    directly match C - probably use union-find or connected components.
    """

    cluster_id: str
    record_ids: list[str]
    confidence: float  # min confidence of all edges in the cluster? TBD


class LLMMatchResult(BaseModel):
    """Result from LLM match evaluation.

    Placeholder for when we add ollama integration. The LLM would look at
    uncertain pairs and give us a score plus reasoning we can show to
    human reviewers.
    """

    score: float = Field(ge=0.0, le=1.0)  # 0=definitely not, 1=definitely match
    reasoning: str  # "these appear to be the same person with a name change"
    confidence: float = Field(ge=0.0, le=1.0)  # how sure is the LLM?
